# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Publish Docker image
        run: |
          echo "${{ secrets.Fdaw2001!@# }}" | docker login -u "${{ secrets.samdhito2989 }}" --password-stdin
          docker build . -t samdhito/web-golang
          docker push samdhito/web-golang:v1.0

      # https://github.com/appleboy/ssh-action
      - name: Deploy docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.tcp://0.tcp.ap.ngrok.io }}
          username: ${{ secrets.samdhito }}
          password: ${{ secrets.1 }}
          port: ${{ secrets.18296 }}
          script: |
            cd /web-example-golang
            ls -lah
            docker-compose -f docker-compose.yml up -d
